In [72]:
import streamlit as st
import matplotlib.pyplot as plt
import pandas as pd
import yfinance as yf
import altair as alt

%matplotlib inline

In [86]:
def get_data(days,tickers):
    df = pd.DataFrame()
    for company in tickers.keys():
        #print(company)
        tkr = yf.Ticker(tickers[company])
        hist = tkr.history(period=f'{days}d')
        hist.index = hist.index.strftime('%d %B %Y')
        hist = hist[['Close']]
        hist.columns = [company]
        hist = hist.T
        hist.index.name = 'Name'
        df = pd.concat([df,hist])
    return df

In [93]:
days = 50

tickers = {
    'apple':'AAPL',
    'Microsoft':'MSFT',
    'google':'GOOGL',
    'Amazon':'AMZN'
}
df = get_data(days,tickers)

In [94]:
companies = ['apple','Microsoft']
data = df.loc[companies]
data.sort_index
data

Date,26 April 2023,27 April 2023,28 April 2023,01 May 2023,02 May 2023,03 May 2023,04 May 2023,05 May 2023,08 May 2023,09 May 2023,...,23 June 2023,26 June 2023,27 June 2023,28 June 2023,29 June 2023,30 June 2023,03 July 2023,05 July 2023,06 July 2023,07 July 2023
Name,,,,,,,,,,,,,,,,,,,,,
apple,163.533798,168.177383,169.445618,169.355743,168.307190,167.218704,165.560989,173.330261,173.260345,171.532745,...,186.679993,185.270004,188.059998,189.250000,189.589996,193.970001,192.460007,191.330002,191.809998,190.679993
Microsoft,294.725708,304.165070,306.589783,304.893494,304.743805,303.736023,304.743805,309.972382,307.976746,306.330353,...,335.019989,328.600006,334.570007,335.850006,335.049988,340.540009,337.989990,338.149994,341.269989,337.220001

In [95]:
data = data.T.reset_index()
data.head()

Name           Date       apple   Microsoft
0     26 April 2023  163.533798  294.725708
1     27 April 2023  168.177383  304.165070
2     28 April 2023  169.445618  306.589783
3       01 May 2023  169.355743  304.893494
4       02 May 2023  168.307190  304.743805

In [96]:
data = pd.melt(data, id_vars=['Date']).rename(
    columns = {'value':'Stock Prices(USD)'}
)    
data

             Date       Name  Stock Prices(USD)
0   26 April 2023      apple         163.533798
1   27 April 2023      apple         168.177383
2   28 April 2023      apple         169.445618
3     01 May 2023      apple         169.355743
4     02 May 2023      apple         168.307190
..            ...        ...                ...
95   30 June 2023  Microsoft         340.540009
96   03 July 2023  Microsoft         337.989990
97   05 July 2023  Microsoft         338.149994
98   06 July 2023  Microsoft         341.269989
99   07 July 2023  Microsoft         337.220001

[100 rows x 3 columns]

In [120]:
ymin,ymax = 200,500
chart = (
    alt.Chart(data)
    .mark_line(opacity = 0.8,clip=True)
    .encode(
        x="Date:T",
        y=alt.Y("Stock Prices(USD):Q",stack = None, scale = alt.Scale(domain=[ymin,ymax])),
        color = 'Name:N'
    )
)

In [121]:
chart

alt.Chart(...)